apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-app
  template:
    metadata:
      labels:
        app: blog-app
    spec:
      volumes:
        - name: my-data
          persistentVolumeClaim:
            claimName: blog-app-pvc
      containers:
        - name: blog-app
          image: mohamedtarekelsayed/blog:1.0 
          command: ["sh", "-c", "python manage.py migrate && python manage.py makemigrations &&  python manage.py createsuperuser --noinput && python manage.py runserver 0.0.0.0:8000"]
          ports:
            - name: http
              containerPort: 8000
          envFrom:
           - configMapRef:
              name: blog-config 

---
apiVersion: v1
kind: Service
metadata:
  name: blog-app-service
spec:
  selector:
    app:  blog-app
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000    
