# persistent-volume.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: blog-app-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: blog-app-pvc
    namespace: default 
  hostPath:
    path: /test

---

# persistent-volume-claim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: blog-app-pv
